=== mongeez/mongeez/src/main/resources/org/mongeez/reader/mongeez-0.9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.mongeez.org/xml/ns/mongeez" 
    xmlns="http://www.mongeez.org/xml/ns/mongeez"
    elementFormDefault="qualified">

    <!-- This is the main (root) part of the xsd -->
    <xsd:element name="changeFiles">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="file" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="mongoChangeLog">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element name="changeSet" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:choice>
                                    <xsd:group ref="changeSetChildren" minOccurs="0" maxOccurs="unbounded" />
                                </xsd:choice>
                            </xsd:sequence>
                            <xsd:attributeGroup ref="changeSetAttributes" />
                            <xsd:anyAttribute namespace="##other" />
                        </xsd:complexType>
                    </xsd:element>
                </xsd:choice>
            </xsd:sequence>
            <xsd:anyAttribute namespace="##other" />
        </xsd:complexType>
    </xsd:element>

    <!-- File element -->
    <xsd:element name="file">
        <xsd:complexType>
            <xsd:attribute name="path" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <!-- Children for changeSet -->
    <xsd:group name="changeSetChildren">
        <xsd:choice>
            <xsd:element name="script" type="xsd:string" maxOccurs="unbounded" />
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
    </xsd:group>

    <!-- Attributes for changeSet -->
    <xsd:attributeGroup name="changeSetAttributes">
        <xsd:attribute name="changeId" type="xsd:string" use="required" />
        <xsd:attribute name="author" type="xsd:string" use="required" />
        <xsd:attribute name="contexts" type="xsd:string" />
        <xsd:attribute name="failOnError" type="xsd:boolean" use="optional" default="true" />
        <xsd:attribute name="runAlways" type="xsd:boolean" use="optional" default="false" />
    </xsd:attributeGroup>

</xsd:schema>

=== mongeez/mongeez/src/test/resources/changeset_with_schema.xml
<mongoChangeLog xmlns="http://www.mongeez.org/xml/ns/mongeez"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mongeez.org/xml/ns/mongeez mongeez-0.9.xsd">
    <changeSet changeId="ChangeSet-1" author="mlysaght" contexts="organizations">
        <script>
            db.organization.insert({
                "Organization" : "10Gen",
                "Location" : "NYC",
                DateFounded : {"Year" : 2008, "Month" : 01, "day" :01}
            });
            db.organization.insert({
                "Organization" : "SecondMarket",
                "Location" : "NYC",
                DateFounded : {"Year" : 2004, "Month" : 05, "day" :04}
            });
        </script>
    </changeSet>
    <changeSet changeId="ChangeSet-2" author="mlysaght" contexts="users">
        <script>
            db.user.insert({ "Name" : "Michael Lysaght"});
        </script>
        <script>
            db.user.insert({ "Name" : "Oleksii Iepishkin"});
        </script>
    </changeSet>
    <changeSet changeId="ChangeSet-3" author="exell">
        <script>
            db.car.insert({ "Type" : "Porsche"});
        </script>
        <script>
            db.car.insert({ "Type" : "Lamborghini"});
        </script>
    </changeSet>
   <changeSet changeId="ChangeSet-4" author="exell" contexts="users, organizations">
        <script>
            db.house.insert({ "Type" : "Bungalow"});
        </script>
        <script>
            db.house.insert({ "Type" : "Split-Level"});
        </script>
    </changeSet>
</mongoChangeLog>
